"""empty message

Revision ID: 07aaaf0a95c6
Revises: 
Create Date: 2023-01-16 17:20:56.332874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07aaaf0a95c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('aim', sa.String(), nullable=True),
    sa.Column('theory', sa.Text(), nullable=True),
    sa.Column('apparatus', sa.String(), nullable=True),
    sa.Column('procedure', sa.Text(), nullable=True),
    sa.Column('result_discussion', sa.String(), nullable=True),
    sa.Column('conclusion', sa.String(), nullable=True),
    sa.Column('precautions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('aim', sa.String(), nullable=True),
    sa.Column('theory', sa.Text(), nullable=True),
    sa.Column('apparatus', sa.String(), nullable=True),
    sa.Column('procedure', sa.Text(), nullable=True),
    sa.Column('result_discussion', sa.String(), nullable=True),
    sa.Column('conclusion', sa.String(), nullable=True),
    sa.Column('precautions', sa.String(), nullable=True),
    sa.Column('experiment_structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_structure_id'], ['experiment_structure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('experiment_structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_structure_id'], ['experiment_structure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values')
    op.drop_table('fields')
    op.drop_table('experiment')
    op.drop_table('experiment_structure')
    # ### end Alembic commands ###
